/**
 * Cross-provider consistency harness (G7.4, 0.3.22; V4-07 0.3.28).
 *
 * Runs the SAME observable operation sequence against an
 * `EvolutionStateStorage` provider (json or domain) and asserts both yield the
 * same field-complete result. Every pending-record field that is carried
 * through a round-trip is compared field by field: id, kind, status, summary,
 * args, createdAt, origin, sessionId, claimedBy. The wall-clock holder stamps
 * (claimedAt, resolvedAt) are generated by each provider at its own transact
 * time and legitimately differ in value between the two claims, so they are
 * asserted only for presence/type (a string), never for equality — and
 * claimedAt is asserted to be cleared on release. Status filtering / release
 * rollback must agree.
 */
import { expect } from 'vitest'
import type { CuratorStateRecord, EvolutionStateStorage, PendingRecord } from '@deepseek-ai/dsh-evolution-state-storage'

/** Build a fixture pending record, optionally carrying origin/sessionId. */
const pendingOf = (
  id: string,
  kind: PendingRecord['kind'] = 'memory',
  attribution: Pick<PendingRecord, 'origin' | 'sessionId'> = {},
): PendingRecord => ({
  id,
  kind,
  summary: `${kind}:${id}`,
  args: {},
  createdAt: 'now',
  status: 'pending',
  ...attribution,
})

/** Every non-holder pending field must equal the input, field by field. */
const expectPendingCarried = (actual: PendingRecord | null | undefined, input: PendingRecord) => {
  expect(actual).toBeDefined()
  expect(actual!.id).toBe(input.id)
  expect(actual!.kind).toBe(input.kind)
  expect(actual!.summary).toBe(input.summary)
  expect(actual!.args).toEqual(input.args)
  expect(actual!.createdAt).toBe(input.createdAt)
  expect(actual!.origin).toBe(input.origin)
  expect(actual!.sessionId).toBe(input.sessionId)
}

export async function runStateProviderConsistency(provider: EvolutionStateStorage): Promise<void> {
  // --- review-state round-trip ---
  await provider.saveReviewState('s-consistent', { turnsSinceMemory: 1, turnsSinceSkill: 2, lastTurn: 3 })
  expect(await provider.loadReviewState('s-consistent')).toEqual({ turnsSinceMemory: 1, turnsSinceSkill: 2, lastTurn: 3 })

  // --- curator-state: missing seed creates; null = keep; overwrite replaces ---
  expect(await provider.loadCuratorState()).toBeNull()
  await provider.transactCuratorState(() => ({ lastRunAt: 10, runCount: 0, lastSummary: 'seed', paused: false }))
  expect(await provider.loadCuratorState()).toEqual({ lastRunAt: 10, runCount: 0, lastSummary: 'seed', paused: false })
  await provider.transactCuratorState(() => null)
  expect(await provider.loadCuratorState()).toEqual({ lastRunAt: 10, runCount: 0, lastSummary: 'seed', paused: false })
  await provider.transactCuratorState(current => ({ ...(current as CuratorStateRecord), lastSummary: 'updated' }))
  expect(await provider.loadCuratorState()).toEqual({ lastRunAt: 10, runCount: 0, lastSummary: 'updated', paused: false })

  // --- claim → resolve (pending → executing → approved) ---
  const live = pendingOf('c-live')
  await provider.savePending(live)
  expect((await provider.listPending('pending')).map(record => record.id)).toContain('c-live')
  const claimed = await provider.claimPending('c-live', 'claim-a')
  expect(claimed?.status).toBe('executing')
  expect(claimed?.claimedBy).toBe('claim-a')
  expectPendingCarried(claimed, live)
  expect(typeof claimed?.claimedAt).toBe('string')
  const resolved = await provider.tryResolvePending('c-live', 'approved')
  expect(resolved.applied).toBe(true)
  expect(resolved.record?.id).toBe('c-live')
  expect(resolved.record?.status).toBe('approved')
  expectPendingCarried(resolved.record, live)
  expect(resolved.record?.claimedBy).toBe('claim-a')
  expect(typeof resolved.record?.claimedAt).toBe('string')
  expect(typeof resolved.record?.resolvedAt).toBe('string')
  expect((await provider.listPending('approved')).map(record => record.id)).toContain('c-live')
  expect((await provider.listPending('pending')).map(record => record.id)).not.toContain('c-live')

  // --- attribution (origin/sessionId) survives claim → resolve ---
  const attrib = pendingOf('c-attrib', 'memory', { origin: 'background_review', sessionId: 'sess-attrib' })
  await provider.savePending(attrib)
  expectPendingCarried(await provider.claimPending('c-attrib', 'claim-a'), attrib)
  const attribResolved = await provider.tryResolvePending('c-attrib', 'approved')
  expectPendingCarried(attribResolved.record, attrib)
  expect(attribResolved.record?.origin).toBe('background_review')
  expect(attribResolved.record?.sessionId).toBe('sess-attrib')
  expect(typeof attribResolved.record?.resolvedAt).toBe('string')

  // --- claim → release rolls executing back to pending (failure path) ---
  const rel = pendingOf('c-release', 'skill')
  await provider.savePending(rel)
  expect((await provider.claimPending('c-release', 'claim-b'))?.status).toBe('executing')
  await provider.releasePendingClaim('c-release', 'claim-b')
  const released = (await provider.listPending('pending')).find(record => record.id === 'c-release')
  expect(released?.status).toBe('pending')
  expectPendingCarried(released, rel)
  expect(released?.claimedBy).toBeUndefined()
  expect(released?.claimedAt).toBeUndefined()

  // --- status filtering is consistent (a pending record is not 'approved') ---
  const filt = pendingOf('c-filter')
  await provider.savePending(filt)
  expect((await provider.listPending('pending')).map(record => record.id)).toContain('c-filter')
  expect((await provider.listPending('approved')).map(record => record.id)).not.toContain('c-filter')

  // --- V8-15 (0.3.46): release AFTER resolve is a no-op on BOTH providers —
  // the resolved record keeps its audit attribution (the domain provider had
  // the status guard; json now matches — G7.4 previously covered only the
  // executing→release path) ---
  const post = pendingOf('c-post-resolve', 'memory')
  await provider.savePending(post)
  await provider.claimPending('c-post-resolve', 'claim-c')
  await provider.tryResolvePending('c-post-resolve', 'rejected')
  await provider.releasePendingClaim('c-post-resolve', 'claim-c')
  const postResolved = (await provider.listPending('rejected')).find(record => record.id === 'c-post-resolve')
  expect(postResolved?.status).toBe('rejected')
  expect(postResolved?.claimedBy).toBe('claim-c')
  expect(typeof postResolved?.claimedAt).toBe('string')
  expect(typeof postResolved?.resolvedAt).toBe('string')
}
