/**
 * Cross-provider consistency harness (G7.4, 0.3.22; V4-07 0.3.28).
 *
 * Runs the SAME observable operation sequence against an
 * `EvolutionStateStorage` provider (json or domain) and asserts both yield the
 * same field-complete result. Every pending-record field that is carried
 * through a round-trip is compared field by field: id, kind, status, summary,
 * args, createdAt, origin, sessionId, claimedBy. The wall-clock holder stamps
 * (claimedAt, resolvedAt) are generated by each provider at its own transact
 * time and legitimately differ in value between the two claims, so they are
 * asserted only for presence/type (a string), never for equality — and
 * claimedAt is asserted to be cleared on release. Status filtering / release
 * rollback must agree. S2-4 (v29): the two seam caps — the resolved pending
 * tail (P2-4) and the review-state session rows (V24-08) — are exercised through
 * the same public operations on both providers, so neither medium can keep the
 * bound to itself.
 */
import { expect } from 'vitest'
import { PENDING_RESOLVED_CAP, REVIEW_STATE_SESSION_CAP } from '@deepseek-ai/dsh-evolution-state-storage'
import type { CuratorStateRecord, EvolutionStateStorage, PendingRecord } from '@deepseek-ai/dsh-evolution-state-storage'

/** Build a fixture pending record, optionally carrying origin/sessionId. */
const pendingOf = (
  id: string,
  kind: PendingRecord['kind'] = 'memory',
  attribution: Pick<PendingRecord, 'origin' | 'sessionId'> = {},
): PendingRecord => ({
  id,
  kind,
  summary: `${kind}:${id}`,
  args: {},
  createdAt: 'now',
  status: 'pending',
  ...attribution,
})

/** Every non-holder pending field must equal the input, field by field. */
const expectPendingCarried = (actual: PendingRecord | null | undefined, input: PendingRecord) => {
  expect(actual).toBeDefined()
  expect(actual!.id).toBe(input.id)
  expect(actual!.kind).toBe(input.kind)
  expect(actual!.summary).toBe(input.summary)
  expect(actual!.args).toEqual(input.args)
  expect(actual!.createdAt).toBe(input.createdAt)
  expect(actual!.origin).toBe(input.origin)
  expect(actual!.sessionId).toBe(input.sessionId)
}

export async function runStateProviderConsistency(provider: EvolutionStateStorage): Promise<void> {
  // --- review-state round-trip ---
  await provider.saveReviewState('s-consistent', { turnsSinceMemory: 1, turnsSinceSkill: 2, lastTurn: 3 })
  expect(await provider.loadReviewState('s-consistent')).toEqual({ turnsSinceMemory: 1, turnsSinceSkill: 2, lastTurn: 3 })

  // --- curator-state: missing seed creates; null = keep; overwrite replaces ---
  expect(await provider.loadCuratorState()).toBeNull()
  await provider.transactCuratorState(() => ({ lastRunAt: 10, runCount: 0, lastSummary: 'seed', paused: false }))
  expect(await provider.loadCuratorState()).toEqual({ lastRunAt: 10, runCount: 0, lastSummary: 'seed', paused: false })
  await provider.transactCuratorState(() => null)
  expect(await provider.loadCuratorState()).toEqual({ lastRunAt: 10, runCount: 0, lastSummary: 'seed', paused: false })
  await provider.transactCuratorState(current => ({ ...(current as CuratorStateRecord), lastSummary: 'updated' }))
  expect(await provider.loadCuratorState()).toEqual({ lastRunAt: 10, runCount: 0, lastSummary: 'updated', paused: false })

  // --- claim → resolve (pending → executing → approved) ---
  const live = pendingOf('c-live')
  await provider.savePending(live)
  expect((await provider.listPending('pending')).map(record => record.id)).toContain('c-live')
  const claimed = await provider.claimPending('c-live', 'claim-a')
  expect(claimed?.status).toBe('executing')
  expect(claimed?.claimedBy).toBe('claim-a')
  expectPendingCarried(claimed, live)
  expect(typeof claimed?.claimedAt).toBe('string')
  const resolved = await provider.tryResolvePending('c-live', 'approved')
  expect(resolved.applied).toBe(true)
  expect(resolved.record?.id).toBe('c-live')
  expect(resolved.record?.status).toBe('approved')
  expectPendingCarried(resolved.record, live)
  expect(resolved.record?.claimedBy).toBe('claim-a')
  expect(typeof resolved.record?.claimedAt).toBe('string')
  expect(typeof resolved.record?.resolvedAt).toBe('string')
  expect((await provider.listPending('approved')).map(record => record.id)).toContain('c-live')
  expect((await provider.listPending('pending')).map(record => record.id)).not.toContain('c-live')

  // --- attribution (origin/sessionId) survives claim → resolve ---
  const attrib = pendingOf('c-attrib', 'memory', { origin: 'background_review', sessionId: 'sess-attrib' })
  await provider.savePending(attrib)
  expectPendingCarried(await provider.claimPending('c-attrib', 'claim-a'), attrib)
  const attribResolved = await provider.tryResolvePending('c-attrib', 'approved')
  expectPendingCarried(attribResolved.record, attrib)
  expect(attribResolved.record?.origin).toBe('background_review')
  expect(attribResolved.record?.sessionId).toBe('sess-attrib')
  expect(typeof attribResolved.record?.resolvedAt).toBe('string')

  // --- claim → release rolls executing back to pending (failure path) ---
  const rel = pendingOf('c-release', 'skill')
  await provider.savePending(rel)
  expect((await provider.claimPending('c-release', 'claim-b'))?.status).toBe('executing')
  await provider.releasePendingClaim('c-release', 'claim-b')
  const released = (await provider.listPending('pending')).find(record => record.id === 'c-release')
  expect(released?.status).toBe('pending')
  expectPendingCarried(released, rel)
  expect(released?.claimedBy).toBeUndefined()
  expect(released?.claimedAt).toBeUndefined()

  // --- E1 (v15): claim-scoped resolve (expectedClaimId) is provider-wide
  // contract — a foreign claimId refuses; the owner succeeds; the unscoped
  // form still works. (v14 shipped this on json with zero domain coverage.) ---
  const scoped = pendingOf('c-scoped')
  await provider.savePending(scoped)
  await provider.claimPending('c-scoped', 'claim-owner')
  const foreignScope = await provider.tryResolvePending('c-scoped', 'approved', 'claim-foreign')
  expect(foreignScope.applied).toBe(false)
  expect((await provider.listPending('executing')).map(record => record.id)).toContain('c-scoped')
  const ownerScope = await provider.tryResolvePending('c-scoped', 'approved', 'claim-owner')
  expect(ownerScope.applied).toBe(true)
  expect(ownerScope.record?.status).toBe('approved')

  // --- status filtering is consistent (a pending record is not 'approved') ---
  const filt = pendingOf('c-filter')
  await provider.savePending(filt)
  expect((await provider.listPending('pending')).map(record => record.id)).toContain('c-filter')
  expect((await provider.listPending('approved')).map(record => record.id)).not.toContain('c-filter')

  // --- V8-15 (0.3.46): release AFTER resolve is a no-op on BOTH providers —
  // the resolved record keeps its audit attribution (the domain provider had
  // the status guard; json now matches — G7.4 previously covered only the
  // executing→release path) ---
  const post = pendingOf('c-post-resolve', 'memory')
  await provider.savePending(post)
  await provider.claimPending('c-post-resolve', 'claim-c')
  await provider.tryResolvePending('c-post-resolve', 'rejected')
  await provider.releasePendingClaim('c-post-resolve', 'claim-c')
  const postResolved = (await provider.listPending('rejected')).find(record => record.id === 'c-post-resolve')
  expect(postResolved?.status).toBe('rejected')
  expect(postResolved?.claimedBy).toBe('claim-c')
  expect(typeof postResolved?.claimedAt).toBe('string')
  expect(typeof postResolved?.resolvedAt).toBe('string')

  // --- I-4 (v18): a malformed record must be REFUSED at the write boundary.
  // Both providers gate writes (json's field gate, domain's zod schema), and
  // C-3 aligned them on the required `args` key — a JS caller or a hand-edited
  // file must not persist a record the other provider would refuse to open. ---
  await expect(provider.savePending({
    id: 'c-bad', kind: 'memory', summary: 'bad', createdAt: 'now', status: 'pending',
  } as PendingRecord)).rejects.toThrow()

  // --- I-4 (v18): mutating a returned record — top level AND nested `args` —
  // must not poison the medium. The domain provider used to hand back live
  // objects, so a caller's edit rewrote the in-memory record before any save
  // (and survived a rejected save). ---
  const poison = pendingOf('c-poison')
  poison.args = { nested: { value: 1 } }
  await provider.savePending(poison)
  const returned = (await provider.listPending('pending')).find(record => record.id === 'c-poison')!
  returned.summary = 'poisoned'
  ;(returned.args as { nested: { value: number } }).nested.value = 99
  const reread = (await provider.listPending('pending')).find(record => record.id === 'c-poison')!
  expect(reread.summary).toBe('memory:c-poison')
  expect((reread.args as { nested: { value: number } }).nested.value).toBe(1)

  // --- P2-15 (v19): a non-cloneable payload is refused by BOTH providers at
  // the write boundary. The domain read path deep-clones every record, so a
  // single poisoned record would break every later read for every status. ---
  await expect(provider.savePending({
    ...pendingOf('c-uncloneable'), args: { fn: () => {} },
  } as unknown as PendingRecord)).rejects.toThrow()

  // --- P2-14 (v19): mutating the CALLER's args after save must not change the
  // stored record (the domain provider used to store the reference). ---
  const aliased = pendingOf('c-alias')
  aliased.args = { nested: { value: 1 } }
  await provider.savePending(aliased)
  ;(aliased.args as { nested: { value: number } }).nested.value = 99
  const aliasedBack = (await provider.listPending('pending')).find(record => record.id === 'c-alias')!
  expect((aliasedBack.args as { nested: { value: number } }).nested.value).toBe(1)

  // --- P2-16 (v19): a malformed schemaVersion is refused by both providers
  // (json used to accept and rewrite it; domain refused it). ---
  await expect(provider.saveCuratorState({
    lastRunAt: 1, runCount: 0, lastSummary: 'x', paused: false, schemaVersion: -1,
  } as unknown as CuratorStateRecord)).rejects.toThrow()

  // --- P2-18 (v19): unknown fields are PRESERVED by both providers (zod's
  // default strip used to delete them on the domain side only). ---
  await provider.savePending({ ...pendingOf('c-extra'), extraField: 'kept' } as unknown as PendingRecord)
  const extraBack = (await provider.listPending('pending')).find(record => record.id === 'c-extra') as unknown as { extraField?: string }
  expect(extraBack.extraField).toBe('kept')

  // --- P2-4 (v15) / C-6 (v18): the RESOLVED pending tail is bounded by the
  // seam constant on the resolve path, on BOTH providers. The vector seeds
  // through the public seam (save then claim then resolve) because json's own
  // cap spec reads its file and the domain medium has no file at all: a
  // medium-specific seed would stop being a shared vector. ---
  const capPrefix = 'c-cap-'
  await provider.savePending(pendingOf('c-cap-live', 'skill'))
  for (let index = 0; index <= PENDING_RESOLVED_CAP + 1; index += 1) {
    const id = capPrefix + String(index).padStart(3, '0')
    await provider.savePending(pendingOf(id))
    await provider.claimPending(id, 'claim-cap')
    await provider.tryResolvePending(id, 'approved')
  }
  const resolvedNow = (await provider.listPending('approved')).concat(await provider.listPending('rejected'))
    .filter(record => record.kind !== 'capability')
  expect(resolvedNow).toHaveLength(PENDING_RESOLVED_CAP)
  const resolvedIds = resolvedNow.map(record => record.id)
  expect(resolvedIds).not.toContain(capPrefix + '000')
  expect(resolvedIds).not.toContain(capPrefix + '001')
  expect(resolvedIds).toContain(capPrefix + String(PENDING_RESOLVED_CAP + 1).padStart(3, '0'))
  expect((await provider.listPending('pending')).map(record => record.id)).toContain('c-cap-live')

  // --- V24-08 (v24): review-state rows are bounded per session table, and the
  // SAVING session is never the victim — one row is dropped per over-cap save,
  // so re-saving the oldest session re-enters it and evicts the next oldest. ---
  const sessionPrefix = 's-cap-'
  const reviewStateOf = (turns: number) => ({ turnsSinceMemory: turns, turnsSinceSkill: 0, lastTurn: turns })
  for (let index = 0; index <= REVIEW_STATE_SESSION_CAP; index += 1) {
    await provider.saveReviewState(sessionPrefix + index, reviewStateOf(index))
  }
  expect(await provider.loadReviewState(sessionPrefix + '0')).toBeNull()
  expect(await provider.loadReviewState(sessionPrefix + '1')).toEqual(reviewStateOf(1))
  expect(await provider.loadReviewState(sessionPrefix + REVIEW_STATE_SESSION_CAP)).toEqual(reviewStateOf(REVIEW_STATE_SESSION_CAP))
  await provider.saveReviewState(sessionPrefix + '0', reviewStateOf(999))
  expect(await provider.loadReviewState(sessionPrefix + '0')).toEqual(reviewStateOf(999))
}
