/**
 * GENERATED by packages/scripts/gen-param-client-view.mjs — do not edit.
 *
 * One card per settings namespace; fields are the E3 rows of the registry, so
 * the browser half names exactly what the Host half registers.
 */

/** One field a card renders a control for. */
export interface ClientParamField {
  id: string
  group: string
  /** The registry summary, used as the field help text. */
  doc: string
}

/** One card: the settings namespace plus the fields it exposes. */
export interface ClientParamSection {
  namespace: string
  fields: readonly ClientParamField[]
}

export const CLIENT_PARAM_SECTIONS: readonly ClientParamSection[] = [
  {
    namespace: 'evolution-curator',
    fields: [
      { id: 'curatorIntervalHours', group: 'curator', doc: 'Minimum hours between deterministic curation passes.' },
      { id: 'staleAfterDays', group: 'curator', doc: 'Inactive days before a skill counts as stale.' },
      { id: 'archiveAfterDays', group: 'curator', doc: 'Inactive days before a stale skill is archived (must be >= staleAfterDays).' },
      { id: 'qualityWarnStaleAfterDays', group: 'curator', doc: 'Age at which a low quality score starts warning.' },
      { id: 'minIdleHours', group: 'curator', doc: 'Idle hours required before an automatic curation pass runs.' },
      { id: 'minIdleFailOpen', group: 'curator', doc: 'Let the idle gate open when the activity probe is unavailable.' },
      { id: 'llmReview', group: 'curator', doc: 'Enable the LLM nomination pass on top of the deterministic lifecycle.' },
      { id: 'curatorReviewMaxTokens', group: 'curator', doc: 'Token budget of the curator LLM review.' },
      { id: 'curatorReviewTimeoutMs', group: 'curator', doc: 'Wall-clock bound of the curator LLM review.' },
      { id: 'healthSoftBodyChars', group: 'curator', doc: 'Body character line the health view judges against.' },
      { id: 'healthStampDensityPerKb', group: 'curator', doc: 'Stamp density per KB that flags log-like content in a body.' },
      { id: 'healthChurnMinPatches', group: 'curator', doc: 'Patches without a read that flag a write-ghost skill.' },
    ],
  },
  {
    namespace: 'evolution-memory',
    fields: [
      { id: 'memoryChars', group: 'memory', doc: 'Character budget the memory store enforces for MEMORY.md.' },
      { id: 'userChars', group: 'memory', doc: 'Character budget the memory store enforces for USER.md.' },
      { id: 'addDatePrefix', group: 'memory', doc: 'Prefix stored memory entries with their date heading.' },
      { id: 'maxConsolidationFailures', group: 'memory', doc: 'Consolidation failures one turn tolerates before the tool gives up.' },
    ],
  },
  {
    namespace: 'evolution-review',
    fields: [
      { id: 'reviewSkillInterval', group: 'review', doc: 'Activity units between skill-review injections.' },
      { id: 'reviewMemoryInterval', group: 'review', doc: 'Activity units between memory-review injections.' },
      { id: 'skillReviewTrigger', group: 'review', doc: 'Which channel may inject a skill review (cadence, completion, both).' },
      { id: 'skillReviewCompletionMinToolCalls', group: 'review', doc: 'Tool calls a task needs before the completion channel injects.' },
      { id: 'reviewEnabled', group: 'review', doc: 'Master switch for the review plugin.' },
      { id: 'reviewMode', group: 'review', doc: 'Run the review in the parent session (inject) or on a subagent.' },
      { id: 'reviewWakeInject', group: 'review', doc: 'Deliver the deferred review as a waking follow-up message.' },
    ],
  },
  {
    namespace: 'evolution-skills',
    fields: [
      { id: 'skillContentChars', group: 'write-caps', doc: 'Character cap on a SKILL.md body (tighten-only).' },
      { id: 'maxSkillFileBytes', group: 'write-caps', doc: 'Byte cap on one support file (tighten-only).' },
      { id: 'maxSkillNameLength', group: 'write-caps', doc: 'Character cap on a skill name (tighten-only).' },
      { id: 'maxDescriptionLength', group: 'write-caps', doc: 'Character cap on a skill description (tighten-only).' },
      { id: 'descriptionStrict', group: 'write-caps', doc: 'Refuse a description over the authoring bar instead of advising.' },
      { id: 'strictCrossSource', group: 'write-caps', doc: 'Refuse writes whose catalog entry resolves outside the family.' },
      { id: 'citationPolicy', group: 'write-caps', doc: 'Refuse a move that would leave a dangling reference, or verify it.' },
      { id: 'referenceRewrite', group: 'write-caps', doc: 'Re-home support files and rewrite references during a merge (plan or apply).' },
      { id: 'archiveRetention', group: 'write-caps', doc: 'Report expired archives, or prune them.' },
      { id: 'supportFileCharPolicy', group: 'write-caps', doc: 'Warn about an oversize support file, or refuse the write.' },
    ],
  },
  {
    namespace: 'evolution-tool-memory',
    fields: [
      { id: 'entryPreviewChars', group: 'memory', doc: 'Characters of one memory entry shown in a tool result preview.' },
    ],
  },
]
